import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Sidebar from "./components/Sidebar";
import "../globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "700",
    "800",
    "900",
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased flex flex-grow w-full h-full`}
      >
        <Sidebar />
        <div className="w-screen h-screen overflow-y-scroll overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
